# FROM dunglas/frankenphp
FROM composer:latest AS composer

WORKDIR /app

COPY composer.json composer.lock /app/
RUN composer install --no-dev --no-interaction --no-progress --no-suggest

FROM php:8.3-cli-alpine

RUN docker-php-ext-install \
    pcntl

COPY --from=composer /app /app
COPY . /app
WORKDIR /app

ENTRYPOINT ["php", "artisan", "octane:frankenphp"]
