services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    command: [ "php", "artisan", "octane:frankenphp", "--host=0.0.0.0", "--port=80" ]
    ports:
      - "8081:80" # HTTP
      # - "443:443" # HTTPS
      # - "443:443/udp" # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - db_data:/app/database # Mount the volume to the database path in the container


# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
  db_data:
