services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - "8081:80" # HTTP
      # - "443:443" # HTTPS
      # - "443:443/udp" # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - db_data:/app/database
      - vendor_data:/app/vendor

  # scheduler:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.production
  #   volumes:
  #     - db_data:/app/database
  #     - vendor_data:/app/vendor
  #   working_dir: /app
  #   entrypoint: /bin/sh -c "while true; do php artisan schedule:run >> /dev/null 2>&1; sleep 60; done"
  #   restart: always

  scheduler:
    image: php:8.3-cli-alpine
    volumes:
      - .:/app
      - vendor_data:/app/vendor
    working_dir: /app
    entrypoint: /bin/sh -c "while true; do php artisan schedule:run >> /dev/null 2>&1; sleep 60; done"
    restart: always


# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
  db_data:
  vendor_data:
