version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.frankenphp.prod
    image: frankenphp-app
    ports:
      - 8082:8000
    entrypoint: php artisan octane:frankenphp

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.php.prod
    image: php-app
    entrypoint: php artisan schedule:run
    depends_on:
      - php
      - postgres
      - redis

  horizon:
    image: php-app
    entrypoint: php artisan horizon
    depends_on:
      - php
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
