version: '3.8'

services:
  php:
    image: dunglas/frankenphp
    restart: always
    ports:
      - "8081:80" # HTTP
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - .:/app
      - sqlite_data:/app/database
  composer:
    image: composer:latest
    volumes:
      - .:/app
    working_dir: /app
  node:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
  sqlite_data:
