FROM dunglas/frankenphp:latest-php8.3-alpine

RUN set -ex \
&& apk --no-cache add \
nodejs \
npm

RUN install-php-extensions pcntl opcache apcu pdo pdo_pgsql redis @composer

ENV SERVER_NAME=:80

COPY . /app

RUN composer install \
    --no-dev \
    --no-interaction \
    --no-ansi \
    --classmap-authoritative \
    --optimize-autoloader \
    --audit \
    && composer clear-cache

RUN npm install && npm run build

ENTRYPOINT ["php", "artisan", "octane:frankenphp"]
