version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php.prod
    image: php-app
    restart: always
    entrypoint: php artisan octane:frankenphp
    ports:
      - 8081:8000
    depends_on:
      - postgres
      - redis

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scheduler:
    image: php-app
    entrypoint: php artisan schedule:run
    depends_on:
      - postgres
      - redis

  horizon:
    image: php-app
    entrypoint: php artisan horizon
    depends_on:
      - postgres
      - redis

  ssr:
    image: php-app
    entrypoint: php artisan inertia:start-ssr
    ports:
      - 144517:144517
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
  caddy_data:
  caddy_config:
