services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - "8081:80" # HTTP
      # - "443:443" # HTTPS
      # - "443:443/udp" # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - db_data:/app/database # Mount the volume to the database path in the container
      - vendor_data:/app/vendor


# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
  db_data:
  vendor_data:
