services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - "8081:80" # HTTP
      # - "443:443" # HTTPS
      # - "443:443/udp" # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - db_data:/app/database
      - vendor_data:/app/vendor
  redis:
    image: dragonflydb/dragonfly
    restart: always
    ports:
      - "6379:6379" # Redis port
    volumes:
      - redis_data:/data

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
  db_data:
  vendor_data:
  redis_data:
